// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warczynski.Zbaszyniak.GroceryApp.SQLDao.DataAccess;

#nullable disable

namespace Warczynski.Zbaszyniak.GroceryApp.DAOMock1.Migrations
{
    [DbContext(typeof(GroceryContext))]
    partial class GroceryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Warczynski.Zbaszyniak.GroceryApp.SQLDao.BO.Grocery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groceries");
                });

            modelBuilder.Entity("Warczynski.Zbaszyniak.GroceryApp.SQLDao.BO.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroceryEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Magnesium")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Potassium")
                        .HasColumnType("REAL");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<float>("Sodium")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GroceryEntityId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Warczynski.Zbaszyniak.GroceryApp.SQLDao.BO.Product", b =>
                {
                    b.HasOne("Warczynski.Zbaszyniak.GroceryApp.SQLDao.BO.Grocery", "GroceryEntity")
                        .WithMany()
                        .HasForeignKey("GroceryEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroceryEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
